kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: argo-rollouts-demo
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  - containerPort: 32000
    hostPort: 8080
    protocol: TCP