apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate
  namespace: {{ .Values.namespace }}
spec:
  metrics:
  - name: error-rate
    interval: 20s
    failureCondition: len(result) > 0 && result[0] >= 5
    failureLimit: 2
    provider:
      prometheus:
        address: http://prometheus-server.prometheus.svc.cluster.local:80
        query: |
          100 * (
          sum(rate(istio_requests_total{destination_service_name="canary-svc", destination_workload=~"rollout-demo-.+", response_code=~"5.*"}[2m])) 
          / 
          sum(rate(istio_requests_total{destination_service_name="canary-svc", destination_workload=~"rollout-demo-.+"}[2m]))
          )
