apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount | default 2 }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.name }}
      release: {{ .Release.Name }}
  strategy:
    canary:
      canaryService: canary-svc
      stableService: stable-svc
      trafficRouting:
        istio:
          virtualService:
            name: rollout-vsvc
            routes:
            - primary
      steps:
      - setWeight: 25
      - pause: {duration: 2m}
      - setWeight: 50
      - pause: {duration: 2m}
      - setWeight: 75
  template:
    metadata:
      annotations: {}
      labels:
        app: {{ .Values.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
          - name: IMAGE_TAG
            value: {{ .Values.image.tag }}
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
          limits:
            memory: 64Mi
            cpu: 10m
        readinessProbe:
          initialDelaySeconds: 2
          httpGet:
            path: /healthz
            port: http