apiVersion: v1
kind: Service
metadata:
  name: canary-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.name }}
    # This selector will be updated by the Argo controler
---
apiVersion: v1
kind: Service
metadata:
  name: stable-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.name }}
    # This selector will be updated by the Argo controler