apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rollout-vsvc
  namespace: {{ .Values.namespace }}
spec:
  gateways:
  - istio-rollout-gateway
  hosts:
  - "*"
  http:
  - name: primary
    route:
    - destination:
        host: stable-svc
        port:
          number: 8080
      weight: 100
    - destination:
        host: canary-svc
        port:
          number: 8080
      weight: 0
