apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rollout-vsvc
  namespace: {{ .Values.namespace }}
spec:
  gateways:
  - istio-rollout-gateway
  hosts:
  - "demo.local"
  http:
  - name: primary
    route:
    - destination:
        host: stable-svc
        port:
          number: 80
      weight: 100
    - destination:
        host: canary-svc
        port:
          number: 80
      weight: 0

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-vsvc
  namespace: {{ .Values.namespace }}
spec:
  gateways:
  - istio-rollout-gateway
  hosts:
  - "127.0.0.1"
  http:
  - name: kiali
    route:
    - destination:
        host: kiali.istio-system.svc.cluster.local
        port:
          number: 20001
